FROM node:20-bookworm

WORKDIR /src

COPY ../ ./
RUN yarn

ARG VITE_PROJECT_ID
ARG VITE_EXPLORER_API_URL
ENV VITE_PROJECT_ID=$VITE_PROJECT_ID
ENV VITE_EXPLORER_API_URL=$VITE_EXPLORER_API_URL
ENV NEXT_PUBLIC_LOG_LEVEL=true
RUN yarn build

RUN yarn playwright:install

# Seems that sometimes Playwright will get stuck on serving the HTML report server
# Setting CI=true will prevent that
ENV CI=true

ENV PRE_BUILD=true
CMD ["yarn", "playwright:test:canary"]
