name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: yarn playwright:install
    - name: Run Playwright tests
      run: yarn playwright:test
      env:
        VITE_PROJECT_ID: ${{ secrets.VITE_DEV_PROJECT_ID }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
